# Generated by Django 5.2.1 on 2025-09-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.CreateModel(
            name='DicaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(verbose_name='Texto da Dica')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicas_nutricionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dica Nutricional',
                'verbose_name_plural': 'Dicas Nutricionais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
